### ISSUE TITLE
Add support for work item backup

### ISSUE THREAD

**Issue by pascalberger** [OrbitOne/VSOBackup#3]
It would be nice to have backup of work items (eg. to excel files) included

**Comment by mdb1988** [comment]
Hi Pascal,

[The VSO Rest API enables you to programatically access work items.](https://www.visualstudio.com/integrate/api/wit/overview) This is a little bit out of scope for us, but feel free to fork the repo and create a pull request! We'd be happy to check it out and maybe integrate it in the current solution.

kind regards,
Maarten
